[package]
name = "randomized-database-indexes"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
protobuf-codegen = "3.7.1"
protoc-bin-vendored = "3.1.0"


[dependencies]

[[bin]]
name = "check_scapegoat"
path = "src/check_scapegoat.rs"